export default [
  {
    _id: "Q101",
    title: "Intro to JavaScript",
    course: "RS101",
    points: 30,
    availableDate: "2024-11-03",
    dueDate: "2024-11-05",
    untilDate: "2024-11-05",
    numberOfQuestions: 3,
    questions: [
      {
        type: "TRUEFALSE",
        content: { text: "Is Jose Cool?", answer: true, point: 10 },
      },
      {
        type: "MULTIPLECHOICE",
        content: {
          text: "What is your favorite color?",
          choices: ["Red", "Blue", "Green", "Orange", "Yellow"],
          answer: "Orange",
          point: 10,
        },
      },
      {
        type: "FILLINTHEBLANK",
        content: {
          text: '"ABC" == "__1__" + "__2__" + "__3__"',
          blanks: ["__1__:", "__2__:", "__3__:"],
          answer: ["A", "B", "C"],
          point: 10,
        },
      },
    ],
    multipleAttempts: true,
    description: "javascript",
    type: "Graded Quiz",
    shuffleAnswers: false,
    oneQuestionPerPage: false,
    timeLimit: "20",
  },
  {
    _id: "Q102",
    title: "Data Structures Basics",
    course: "RS101",
    points: 50,
    availableDate: "2024-11-12",
    dueDate: "2024-11-15",
    numberOfQuestions: 0,
    questions: [],
    multipleAttempts: false,
    description: "data structures",
    type: "Graded Quiz",
    shuffleAnswers: false,
    oneQuestionPerPage: false,
    timeLimit: "20",
  },
  {
    _id: "Q103",
    title: "Advanced Algorithms",
    course: "RS101",
    points: 120,
    availableDate: "2024-10-20",
    dueDate: "2024-10-25",
    numberOfQuestions: 0,
    questions: [],
    multipleAttempts: false,
    description: "algo",
    type: "Graded Quiz",
    shuffleAnswers: false,
    oneQuestionPerPage: false,
    timeLimit: "20",
  },
];
